import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Share,
  Alert,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { router, useLocalSearchParams } from 'expo-router';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Colors } from '@/constants/Colors';
import { Fonts } from '@/constants/Fonts';
import { 
  ArrowLeft, 
  Share2, 
  Download, 
  Star, 
  Clock, 
  CheckCircle2,
  AlertTriangle,
  Info,
  Calendar,
  Award,
  Target,
  BookOpen
} from 'lucide-react-native';

interface SessionSummary {
  session_title: string;
  main_topic: string;
  urgency_level: 'low' | 'moderate' | 'high';
  key_points: string[];
  recommendations: string[];
  techniques_taught: string[];
  next_steps: string[];
  progress_notes: string;
  follow_up_timeline: string;
}

export default function CoachSummaryScreen() {
  const params = useLocalSearchParams();
  const [rating, setRating] = useState(0);
  
  // Parse summary from params
  const summary: SessionSummary = JSON.parse(params.summary as string);
  const sessionId = params.sessionId as string;

  const getUrgencyColor = (level: string) => {
    switch (level) {
      case 'high': return '#ff4444';
      case 'moderate': return '#ff9d00';
      case 'low': return '#4CAF50';
      default: return Colors.primary;
    }
  };

  const getUrgencyIcon = (level: string) => {
    switch (level) {
      case 'high': return <AlertTriangle size={20} color="#ff4444" />;
      case 'moderate': return <Info size={20} color="#ff9d00" />;
      case 'low': return <CheckCircle2 size={20} color="#4CAF50" />;
      default: return <Info size={20} color={Colors.primary} />;
    }
  };

  const handleShare = async () => {
    try {
      const shareContent = `
🐾 VetPaw Coaching Summary

Session: ${summary.session_title}
Topic: ${summary.main_topic}

📝 Key Recommendations:
${summary.recommendations.map((rec, index) => `${index + 1}. ${rec}`).join('\n')}

🎯 Next Steps:
${summary.next_steps.map((step, index) => `${index + 1}. ${step}`).join('\n')}

Follow-up: ${summary.follow_up_timeline}

Generated by VetPaw AI Coaching with James 🎓
      `.trim();

      await Share.share({
        message: shareContent,
        title: 'VetPaw Coaching Summary',
      });
    } catch (error) {
      console.error('Error sharing summary:', error);
      Alert.alert('Error', 'Failed to share summary. Please try again.');
    }
  };

  const handleRating = (selectedRating: number) => {
    setRating(selectedRating);
    // Here you would typically save the rating to the database
    console.log('Session rated:', selectedRating);
  };

  const formatList = (items: string[], icon: string) => {
    return items.map((item, index) => (
      <View key={index} style={styles.listItem}>
        <Text style={styles.listIcon}>{icon}</Text>
        <Text style={styles.listText}>{item}</Text>
      </View>
    ));
  };

  return (
    <View style={styles.container}>
      <LinearGradient
        colors={['#FFF8E1', '#ffffff']}
        style={styles.backgroundGradient}
      />
      
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity 
          style={styles.backButton}
          onPress={() => router.back()}
        >
          <ArrowLeft size={24} color="#544c3a" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Session Summary</Text>
        <TouchableOpacity 
          style={styles.shareButton}
          onPress={handleShare}
        >
          <Share2 size={24} color="#ff9d00" />
        </TouchableOpacity>
      </View>

      <ScrollView 
        style={styles.scrollView}
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.scrollContent}
      >
        {/* Session Header */}
        <Card variant="elevated" style={styles.sessionHeader}>
          <View style={styles.sessionTitleRow}>
            <Award size={24} color="#ff9d00" />
            <View style={styles.sessionTitleContainer}>
              <Text style={styles.sessionTitle}>{summary.session_title}</Text>
              <Text style={styles.sessionTopic}>{summary.main_topic}</Text>
            </View>
          </View>
          
          <View style={styles.urgencyContainer}>
            {getUrgencyIcon(summary.urgency_level)}
            <Text style={[styles.urgencyText, { color: getUrgencyColor(summary.urgency_level) }]}>
              {summary.urgency_level.toUpperCase()} PRIORITY
            </Text>
          </View>
        </Card>

        {/* Progress Notes */}
        {summary.progress_notes && (
          <Card variant="elevated" style={styles.progressCard}>
            <View style={styles.sectionHeader}>
              <BookOpen size={20} color="#ff9d00" />
              <Text style={styles.sectionTitle}>Session Notes</Text>
            </View>
            <Text style={styles.progressNotes}>{summary.progress_notes}</Text>
          </Card>
        )}

        {/* Key Points */}
        {summary.key_points && summary.key_points.length > 0 && (
          <Card variant="elevated" style={styles.keyPointsCard}>
            <View style={styles.sectionHeader}>
              <CheckCircle2 size={20} color="#ff9d00" />
              <Text style={styles.sectionTitle}>Key Discussion Points</Text>
            </View>
            <View style={styles.listContainer}>
              {formatList(summary.key_points, '💡')}
            </View>
          </Card>
        )}

        {/* Recommendations */}
        {summary.recommendations && summary.recommendations.length > 0 && (
          <Card variant="elevated" style={styles.recommendationsCard}>
            <View style={styles.sectionHeader}>
              <Target size={20} color="#ff9d00" />
              <Text style={styles.sectionTitle}>James's Recommendations</Text>
            </View>
            <View style={styles.listContainer}>
              {formatList(summary.recommendations, '🎯')}
            </View>
          </Card>
        )}

        {/* Techniques Taught */}
        {summary.techniques_taught && summary.techniques_taught.length > 0 && (
          <Card variant="elevated" style={styles.techniquesCard}>
            <View style={styles.sectionHeader}>
              <Award size={20} color="#ff9d00" />
              <Text style={styles.sectionTitle}>Techniques Covered</Text>
            </View>
            <View style={styles.listContainer}>
              {formatList(summary.techniques_taught, '📚')}
            </View>
          </Card>
        )}

        {/* Next Steps */}
        {summary.next_steps && summary.next_steps.length > 0 && (
          <Card variant="elevated" style={styles.nextStepsCard}>
            <View style={styles.sectionHeader}>
              <Calendar size={20} color="#ff9d00" />
              <Text style={styles.sectionTitle}>Your Next Steps</Text>
            </View>
            <View style={styles.listContainer}>
              {formatList(summary.next_steps, '✅')}
            </View>
            
            {summary.follow_up_timeline && (
              <View style={styles.followUpContainer}>
                <Clock size={16} color="#7a6f5d" />
                <Text style={styles.followUpText}>
                  Follow-up: {summary.follow_up_timeline}
                </Text>
              </View>
            )}
          </Card>
        )}

        {/* Session Rating */}
        <Card variant="elevated" style={styles.ratingCard}>
          <Text style={styles.ratingTitle}>How was your session with James?</Text>
          <Text style={styles.ratingSubtitle}>Your feedback helps us improve</Text>
          
          <View style={styles.starsContainer}>
            {[1, 2, 3, 4, 5].map((star) => (
              <TouchableOpacity
                key={star}
                onPress={() => handleRating(star)}
                style={styles.starButton}
              >
                <Star
                  size={32}
                  color={star <= rating ? '#ff9d00' : '#e0e0e0'}
                  fill={star <= rating ? '#ff9d00' : 'transparent'}
                />
              </TouchableOpacity>
            ))}
          </View>
          
          {rating > 0 && (
            <Text style={styles.ratingFeedback}>
              {rating === 5 ? 'Excellent! 🎉' :
               rating === 4 ? 'Great session! 👏' :
               rating === 3 ? 'Good session 👍' :
               rating === 2 ? 'Could be better 🤔' :
               'We\'ll work to improve 💪'}
            </Text>
          )}
        </Card>

        {/* Action Buttons */}
        <View style={styles.actionsContainer}>
          <Button
            title="Book Another Session"
            onPress={() => router.push('/coach/intro')}
            style={styles.primaryButton}
          />
          
          <TouchableOpacity 
            style={styles.secondaryButton}
            onPress={() => router.push('/coach/history')}
          >
            <Text style={styles.secondaryButtonText}>View All Sessions</Text>
          </TouchableOpacity>
        </View>

        {/* Tips */}
        <Card variant="outlined" style={styles.tipsCard}>
          <Text style={styles.tipsTitle}>💡 Coaching Tips</Text>
          <Text style={styles.tipsText}>
            • Practice the techniques James taught you daily{'\n'}
            • Be consistent with your training approach{'\n'}
            • Celebrate small wins with your furry friend{'\n'}
            • Book follow-up sessions to build on your progress
          </Text>
        </Card>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF8E1',
  },
  backgroundGradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: Fonts.heading.bold,
    color: '#544c3a',
  },
  shareButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  sessionHeader: {
    marginBottom: 16,
  },
  sessionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  sessionTitleContainer: {
    flex: 1,
    marginLeft: 12,
  },
  sessionTitle: {
    fontSize: 18,
    fontFamily: Fonts.heading.bold,
    color: '#544c3a',
    marginBottom: 4,
  },
  sessionTopic: {
    fontSize: 14,
    fontFamily: Fonts.body.medium,
    color: '#7a6f5d',
  },
  urgencyContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f8f8',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  urgencyText: {
    fontSize: 12,
    fontFamily: Fonts.body.bold,
    marginLeft: 6,
  },
  progressCard: {
    marginBottom: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: Fonts.heading.semiBold,
    color: '#544c3a',
    marginLeft: 8,
  },
  progressNotes: {
    fontSize: 14,
    fontFamily: Fonts.body.regular,
    color: '#544c3a',
    lineHeight: 20,
  },
  keyPointsCard: {
    marginBottom: 16,
  },
  recommendationsCard: {
    marginBottom: 16,
  },
  techniquesCard: {
    marginBottom: 16,
  },
  nextStepsCard: {
    marginBottom: 16,
  },
  listContainer: {
    gap: 12,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  listIcon: {
    fontSize: 16,
    marginRight: 8,
    marginTop: 2,
  },
  listText: {
    flex: 1,
    fontSize: 14,
    fontFamily: Fonts.body.regular,
    color: '#544c3a',
    lineHeight: 20,
  },
  followUpContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  followUpText: {
    fontSize: 14,
    fontFamily: Fonts.body.medium,
    color: '#7a6f5d',
    marginLeft: 6,
  },
  ratingCard: {
    marginBottom: 20,
    alignItems: 'center',
  },
  ratingTitle: {
    fontSize: 18,
    fontFamily: Fonts.heading.semiBold,
    color: '#544c3a',
    marginBottom: 4,
  },
  ratingSubtitle: {
    fontSize: 14,
    fontFamily: Fonts.body.regular,
    color: '#7a6f5d',
    marginBottom: 20,
  },
  starsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 16,
  },
  starButton: {
    padding: 4,
    marginHorizontal: 4,
  },
  ratingFeedback: {
    fontSize: 16,
    fontFamily: Fonts.body.medium,
    color: '#ff9d00',
    textAlign: 'center',
  },
  actionsContainer: {
    marginBottom: 20,
  },
  primaryButton: {
    marginBottom: 12,
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#ff9d00',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontSize: 16,
    fontFamily: Fonts.body.semiBold,
    color: '#ff9d00',
  },
  tipsCard: {
    borderColor: '#ff9d00',
  },
  tipsTitle: {
    fontSize: 16,
    fontFamily: Fonts.heading.semiBold,
    color: '#544c3a',
    marginBottom: 12,
  },
  tipsText: {
    fontSize: 14,
    fontFamily: Fonts.body.regular,
    color: '#7a6f5d',
    lineHeight: 20,
  },
});
